#define PICASSO_LIB
#include "picasso_global.h"

#include "picasso_api.cpp"
#include "picasso_canvas.cpp"
#include "picasso_font.cpp"
#include "picasso_font_api.cpp"
#include "picasso_gradient.cpp"
#include "picasso_gradient_api.cpp"
#include "picasso_image.cpp"
#include "picasso_mask.cpp"
#include "picasso_mask_api.cpp"
#include "picasso_matrix.cpp"
#include "picasso_matrix_api.cpp"
#include "picasso_painter.cpp"
#include "picasso_path.cpp"
#include "picasso_pattern.cpp"
#include "picasso_raster_adapter.cpp"
#include "picasso_rendering_buffer.cpp"

#include "core/curve.cpp"
#include "core/device.cpp"
#include "core/fixedopt.cpp"
#include "core/gpc.cpp"
#include "core/graphic_path.cpp"

#include "gfx/gfx_blur.cpp"
#include "gfx/gfx_device.cpp"
#include "gfx/gfx_font_adapter_freetype2.cpp"
#include "gfx/gfx_font_adapter_win32.cpp"
#include "gfx/gfx_font_load_freetype2.cpp"
#include "gfx/gfx_gradient_adapter.cpp"
#include "gfx/gfx_image_filters.cpp"
#include "gfx/gfx_raster_adapter.cpp"
#include "gfx/gfx_rendering_buffer.cpp"
#include "gfx/gfx_sqrt_tables.cpp"
